name: 'Matrix CD Template'
description: 'Matrix CD Template'
author: 'lwnmengjing'
inputs:
  import-env-names:
    required: true
    description: 'envs need to pass to container'
    default: '["STAGE"]'
  app:
    required: true
    description: 'app name'
    default: 'matrixworld'
  service:
    required: true
    description: 'service name'
    default: 'account'
  port:
    required: true
    description: 'http port'
    default: '8000'
  version:
    required: true
    description: 'app version'
    default: 'v1'
  image-name:
    required: true
    description: 'image name'
    default: 'image'
  image-tag:
    required: true
    description: 'image tag'
    default: 'latest'
  deploy-namespace:
    required: true
    description: 'namespace'
    default: 'default'
runs:
#  using: 'node12'
#  pre: 'setup.js'
#  main: 'main.js'
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
    - run: yarn && tsc
      shell: bash
    - uses: ./
      with:
        import-env-names: ${{ inputs.import-env-names }}
        app: ${{ inputs.app }}
        service: ${{ inputs.service }}
        port: ${{ inputs.port }}
        version: ${{ inputs.version }}
        image-name: ${{ inputs.image-name }}
        image-tag: ${{ inputs.image-tag }}
        deploy-namespace: ${{ inputs.deploy-namespace }}
      run: node main.js
    - uses: canastro/copy-file-action@master
      with:
        source: dist
        target: ${{ github.workspace }}/
