name: "Pull Request Labeler"

on:
  - pull_request_target

jobs:
  triage:
    runs-on: [self-hosted, dind]
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
