on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  template:
    runs-on: ubuntu-latest
    name: template
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build cdk8s
        uses: ./ # Uses an action in the root directory
        id: cdk8s
        env:
          IMAGE_NAME: 043446723194.dkr.ecr.ap-northeast-1.amazonaws.com/matrix-cloud-cicd-template
          IMAGE_TAG: latest
          DEPLOY_NAMESPACE: default
          STAGE: beta
          port-name: http
          container-port: '8000'
          target-port: '8000'
          version: v1
          metrics-scrape: true
          metrics-port: '15014'
          metrics-path: '/metrics'
      # Use the output from the `hello` step
      - name: Get the output
        run: ls
